version: '1.0.{build}'

branches:
  only:
  - master
  - Development

configuration:
- Debug
- Release

platform: Any CPU

environment:
  # Don't report back to the mothership
  DOTNET_CLI_TELEMETRY_OPTOUT: 1
  SNK_PASSPHRASE:
    secure: hAvbiLFI38bO0EdEXv77Xk0P3slfTlGq+jaD5JY0VaE=
  SNK_SALT:
    secure: F/vXSd1ELO8L1EkLnaFLgoWgayckxYQmtnWqa/CI05M=
  SNK_INIT:
    secure: i+0xK/acnRfh2XY8FjUR9LPlbP+HyPadahLxlrQnB58=


init:
- ps: $Env:LABEL = "CI" + $Env:APPVEYOR_BUILD_NUMBER.PadLeft(5, "0")

before_build:
- appveyor-retry dotnet restore -v Minimal
- ps: C:\projects\jmespath-net\bin\EncryptDecryptFile.PS1
- ps: Decrypt-File "C:\projects\jmespath-net\src\jmespath.net.signed\jmespath.net.snk" -Passphrase $env:SNK_PASSPHRASE -salt $env:SNK_SALT -init $env:SNK_INIT  -outputPath "C:\projects\jmespath-net\src\jmespath.net.signed\jmespath.net.snk"

build_script:
- dotnet build "src\jmespath.net" -c %CONFIGURATION% --no-dependencies --version-suffix %LABEL%
- dotnet build "src\jmespath.net.signed" -c %CONFIGURATION% --no-dependencies --version-suffix %LABEL%

after_build:

test_script:
- dotnet test "tests\jmespathnet.tests" -c %CONFIGURATION%

cache:
- '%USERPROFILE%\.nuget\packages'

on_finish:
